services:
  - type: web
    name: crop-recommendation-system
    env: python
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT